name: Deploy dg-analysis

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: deployguard-analysis
  CONTAINER_NAME: deployguard-analysis

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::189060532132:role/deployguard-analysis-github-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract Git SHA
        id: meta
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.meta.outputs.sha_short }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.meta.outputs.sha_short }}
        run: |
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Deploy container
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |

          echo "Pull latest image"
          docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest

          echo "Stop old container"
          docker stop deployguard-analysis || true

          echo "Remove old container"
          docker rm deployguard-analysis || true

          echo "Run new container"
          docker run -d \
            --restart unless-stopped \
            --name deployguard-analysis \
            -p 8000:8000 \
            -e AWS_REGION=ap-northeast-2 \
            -e S3_BUCKET_NAME=dg-raw-scans \
            -e DATABASE_URL="${{ secrets.DATABASE_URL }}" \
            $ECR_REGISTRY/$ECR_REPOSITORY:latest

          echo "Cleanup unused images"
          docker image prune -af